### ISSUE TITLE
Wrong setup script?

### ISSUE THREAD

**Issue by denis-ldv** [OpenNebula/addon-lvm#1]
I unzipped archive with addon to /root then
```
# ./install.sh -d  /var/lib/one
cp: cannot stat ‘/root/LVM_addon/src/datastore/lvm’: No such file or directory
cp: cannot stat ‘/root/LVM_addon/src/tm/lvm’: No such file or directory

```

**Comment by chr4** [comment]
+1

**Comment by chr4** [comment]
https://github.com/OpenNebula/addon-lvm/blob/master/install.sh#L20
This comment indicates that it's actually the script from the Xen plugin - Maybe it's not finished yet?
